# Schema for the configuration files of the od_ext_analytics module.

views.view.google_analytics_api:
  type: views_display_default
  label: 'Default display options'
  mapping:
    display_options:
      type: mapping
      label: 'Display options'
      mapping:
        filters:
          type: mapping
          label: 'Filters'
          mapping:
            start_date:
              type: mapping
              label: 'Start Date'
              mapping:
                value:
                  type: mapping
                  label: 'Context Value'
                  mapping:
                    type:
                      type: string
                      label: 'Type'
                    value:
                      type: string
                      label: 'Value'
            end_date:
              type: mapping
              label: 'End Date'
              mapping:
                value:
                  type: mapping
                  label: 'Context Value'
                  mapping:
                    type:
                      type: string
                      label: 'Type'
                    value:
                      type: string
                      label: 'Value'
